### ISSUE TITLE
Compilation failed: Unable to find a set of packages that will work with your constraints.

### ISSUE THREAD

**Issue by mathiasverraes** [tcoopman/elm-maze#1]
```
   ...
   [76] ./src/index.js 124 bytes {0} [built] [1 error]

ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
Unable to find a set of packages that will work with your constraints.

    at ChildProcess.<anonymous> (/Users/mathias/workspace/elm/elm-maze/node_modules/node-elm-compiler/index.js:181:27)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
 @ ./src/index.js 2:10-29
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 524 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 1.48 kB {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 523 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
```

**Comment by tcoopman** [comment]
@mathiasverraes what version of Elm do you have installed? You need at least 0.17.
I've updated the README.

**Comment by mathiasverraes** [comment]
upgraded 0.17.0 -> 0.17.1, same issue.

**Comment by tcoopman** [comment]
can you run `elm-make src/Main.elm` and print the output?

**Comment by mathiasverraes** [comment]
```
> elm-make src/Main.elm
Unable to find a set of packages that will work with your constraints.
```

And npm:

```
> npm start

> elm-maze@1.0.0 start /Users/mathias/workspace/elm/elm-maze
> webpack-dev-server --hot --inline --content-base src/

http://localhost:8080/
webpack result is served from /
content is served from /Users/mathias/workspace/elm/elm-maze/src
Running elm-make /Users/mathias/workspace/elm/elm-maze/src/Main.elm --yes
--warn --output
/var/folders/yd/5y8r5z2940gff032qbbbsstc0000gn/T/11677-25002-tp3e6g.js
Hash: 952f209ff6aa0c1b7d3a
Version: webpack 1.13.1
Time: 1358ms
                  Asset     Size  Chunks             Chunk Names
952f209ff6aa0c1b7d3a.js   257 kB       0  [emitted]  main
             index.html  1.13 kB          [emitted]
chunk    {0} 952f209ff6aa0c1b7d3a.js (main) 218 kB [rendered]
    [0] multi main 64 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:8080 2.67 kB {0}
[built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [10] ./~/sockjs-client/lib/transport/websocket.js 2.71 kB {0} [built]
   [11] ./~/process/browser.js 3.21 kB {0} [built]
   [12] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [13] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [14] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [15] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [16] ./~/url-parse/index.js 8.09 kB {0} [built]
   [17] ./~/requires-port/index.js 753 bytes {0} [built]
   [18] ./~/url-parse/lolcation.js 1.58 kB {0} [built]
   [19] ./~/querystringify/index.js 1.3 kB {0} [built]
   [20] ./~/debug/browser.js 3.76 kB {0} [built]
   [21] ./~/debug/debug.js 4.1 kB {0} [built]
   [22] ./~/ms/index.js 2.33 kB {0} [built]
   [23] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [24] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [25] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [26] ./~/sockjs-client/lib/transport/browser/websocket.js 172 bytes {0}
[built]
   [27] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [28] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0}
[built]
   [29] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.15 kB {0}
[built]
   [30] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0}
[built]
   [31] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [33] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0}
[built]
   [34] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0}
[built]
   [35] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0}
[built]
   [36] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [37] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0}
[built]
   [38] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [39] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [40] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0}
[built]
   [41] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0}
[built]
   [42] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0}
[built]
   [43] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [44] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [45] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [46] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [47] ./~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [48] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [49] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [50] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0}
[built]
   [51] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [52] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [53] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [54] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0}
[built]
   [55] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [56] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [57] ./~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [58] ./~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [59] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [60] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [61] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [62] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [63] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [64] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [65] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [66] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0}
[built]
   [67] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [68] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [69] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [70] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [71] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [72] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [73] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [74] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
   [75] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]
   [76] ./src/index.js 124 bytes {0} [built] [1 error]

ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation
failed
Unable to find a set of packages that will work with your constraints.

    at ChildProcess.<anonymous>
(/Users/mathias/workspace/elm/elm-maze/node_modules/node-elm-compiler/index.js:181:27)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
 @ ./src/index.js 2:10-29
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 524 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 1.48 kB
{0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 523 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
```

**Comment by tcoopman** [comment]
really weird. What does `elm-package install` say?

**Comment by mathiasverraes** [comment]
Same thing.

**Comment by tcoopman** [comment]
Can you try to delete the `elm-stuff` directory and then try `elm-package
install` again?

**Comment by mathiasverraes** [comment]
So, apparently I managed to have two installations of elm 0.17.0. I had updated the wrong one.  Sorry for the trouble.
